# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: web-application-service
spec:
  selector:
    app: web-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

